
name: DependencyTrack Upload SBOM
on: push
permissions:
  contents: read

jobs:
  dependencytrack-sbom-upload:
    permissions:
      actions: write  # for anchore/sbom-action to upload workflow artifacts
      contents: write  # for anchore/sbom-action to upload & delete release assets
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@ab5d7b5f48981941c4c5d6bf33aeb98fe3bae38c # v0.15.10
      with:
        image: grafana/grafana-oss:10.4.1
        artifact-name: sbom.cdx.json
        output-file: ./sbom.cdx.json
        format: cyclonedx-json
    - name: Upload SBOMs
      working-directory: "."
      run: |
            echo "::add-mask::${{ secrets.DEPENDENCYTRACK_API_KEY }}"
            curl -sS -X "POST" "https://${{ secrets.DEPENDENCYTRACK_HOSTNAME }}/api/v1/bom" \
                -H "Content-Type: multipart/form-data" \
                -H "X-Api-Key: ${{ secrets.DEPENDENCYTRACK_API_KEY }}" \
                -F "autoCreate=true" \
                -F "projectName=${{ github.repository }}" \
                -F "projectVersion=master" \
                -F "bom=@sbom.cdx.json"